### ISSUE TITLE
Include Java Language Server 

### ISSUE THREAD

**Issue by mrmcq2u** [flathub/org.freedesktop.Sdk.Extension.openjdk11#10]
https://github.com/georgewfraser/java-language-server/issues/93 , Would it be ok for you to include the language sever as part of the extension? Seems to be blocking https://gitlab.gnome.org/GNOME/gnome-builder/merge_requests/183

**Comment by TingPing** [comment]
Just build it in builder, why does it need to be here?

EDIT: I see christians comment he doesn't want to bundle java, but that is fine as he says it can be an extension for gnome-builder.

**Comment by mbooth101** [comment]
Not unless you tell me more about it. What does "javals relies on a custom JRE" mean? I am not inclined to patch the JRE for every random project...

**Comment by mbooth101** [comment]
I'm going to close this. I'm not inclined to ship a language server with the JDK. I recommend you check out https://github.com/eclipse/eclipse.jdt.ls, which is quite mature now; many projects have integrated that Java language server without the need for any custom JRE.
