### ISSUE TITLE
Download JDK from updated repository instead of using stale build

### ISSUE THREAD

**Issue by matteo-gallo-bb** [flathub/org.freedesktop.Sdk.Extension.openjdk11#17]
Please use an updated JDK tar instead of the current stale one (https://hg.openjdk.java.net/shenandoah/jdk11/archive/shenandoah-jdk-11.0.8+10.tar.gz) since this one is clearly stating: "This JDK will not get security, functionality, or performance fixes."
See link: https://hg.openjdk.java.net/shenandoah/jdk11/rev/8e3f5859da54

We could use latest JDK 11.0.9 from Debian (https://packages.debian.org/buster/openjdk-11-jdk) as its builds have Shenandoah enabled according to: https://wiki.openjdk.java.net/display/shenandoah/Main#Main-Releases.

Also other tars used for bootstrap-java have old 11.0.5 version, please update those as well.

**Comment by mbooth101** [comment]
Yes, shenandoah was merged into mainline for 11.0.9

Updated to 11.0.11 in 7df45e0a96660a7ab8a0d9eeb7215ed62a690cab

The bootstrap version is irrelevant, nothing from the bootstrap tarball makes it into flathub.
