### ISSUE TITLE
Unable to find shared object files

### ISSUE THREAD

**Issue by mpi3d** [flathub/org.freedesktop.Sdk.Extension.openjdk11#24]
Hi,

I'm working on [flathub/org.ghidra_sre.Ghidra](https://github.com/flathub/org.ghidra_sre.Ghidra). Unfortunately, it seems that Java is unable to find `.so` files located in `/usr/lib/x86_64-linux-gnu` (And maybe other locations too)
For example, it can't find `libutil.so`:
```
2022-06-01 21:16:31 ERROR (DebuggerConnectDialog) Could not connect: java.lang.UnsatisfiedLinkError: libutil.so: cannot open shared object file: No such file or directory
```

I'm able to solve this by adding `LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu` in the environment.

But `/usr/lib/x86_64-linux-gnu` is already configured in `ld.so.conf`. So it sounds more like a bug.

The original issue is flathub/org.ghidra_sre.Ghidra#26.

Thanks.

**Comment by hadess** [comment]
FWIW, I couldn't reproduce this problem.

**Comment by mpi3d** [comment]
Issue seems to be resolved.
