### ISSUE TITLE
22.08 OpenJDK 11

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.freedesktop.Sdk.Extension.openjdk11#27]
There is already a pull request(https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/26), but sadly that won't do. The maintainer of this project will have to make a new branch and they should then update the OpenJDK extension.

**Comment by hadess** [comment]
The runtime was updated in f43518b8f0694cd9ced9ec909c3ca50fcd2dec59 and the `branch/22.08` branch.

**Comment by hfiguiere** [comment]
it has been out. closing
