### ISSUE TITLE
Outstanding security issues OpenJDK 8, OpenJDK 11, OpenJDK 17

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.freedesktop.Sdk.Extension.openjdk11#34]
@barthalion @nedrichards @TingPing @hfiguiere Forgive me for dragging you all into this

We have some outstanding security troubles. The OpenJDK packages lack proper maintenance. Not just OpenJDK 11, but also multiple freedesktop-versions, and also for JDK 8 and JDK 17.

OpenJDK 11.016 for example:

https://www.oracle.com/java/technologies/javase/11-0-17-relnotes.html
https://www.oracle.com/java/technologies/javase/11-0-18-relnotes.html

Similar problems exist with OpenJDK 8 and OpenJDK 17. Some people have already contributed some merge-requests, but I would argue that OpenJDK is a little too important to just 'wait around until we get a pull request'. We need to get our heads together and we need to make sure that all currently supported OpenJDK versions remain well patched.

I'm not sure who has enough time or knowledge to supervise such a project. I often work with OpenJDK, but I've never actually built it myself so I'm not sure if I should be the responsible one. Besides, I already have quite a few projects under my wing so my time is limited.

Either way, let's see if we can discuss the outstanding patches

**Comment by Eonfge** [comment]
Since [discovering](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/33) this issue two weeks ago, the patches for OpenJDK 8 have been applied: 
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/pulls?q=is%3Apr+is%3Aclosed

Still, the patches for OpenJDK 11 and 17 are still pending;

https://www.oracle.com/java/technologies/javase/17-0-5-relnotes.html
https://www.oracle.com/java/technologies/javase/17-0-6-relnotes.html

**Comment by Eonfge** [comment]
@MatMaul I really don't want to escalate this issue further, I've already emailed to the administrators @ flathub, but if I fail to get anybodies attention on these outstanding security issues, then I'll have to make more noise.

**Comment by MatMaul** [comment]
I am happy to be promoted maintainer on the LTS versions of the JVM, if it helps. I don't promise that I will always timely push updates, but I'll take care to merge PRs and try my best with the time I have.

**Comment by MatMaul** [comment]
@Eonfge I have been promoted maintainer of openjdk11 and 17, this issue can be closed I believe. Update to 11 has been merged, I am updated 17 right now. Thanks for pushing that, it has been lingering around for too long.
