### ISSUE TITLE
Ant is not installed

### ISSUE THREAD

**Issue by Mailaender** [flathub/org.freedesktop.Sdk.Extension.openjdk11#36]
> /bin/sh: line 1: /usr/bin/ant: No such file or directory

**Comment by cxrvh** [comment]
How are you accessing ant? It's working on my system if enabled:
> [📦 org.freedesktop.Sdk ~]$ ant
bash: ant: command not found
[📦 org.freedesktop.Sdk ~]$ . /usr/lib/sdk/openjdk11/enable.sh 
[📦 org.freedesktop.Sdk ~]$ ant -version
Apache Ant(TM) version 1.10.13 compiled on January 4 2023

**Comment by hfiguiere** [comment]
`/usr/bin/ant`. that's unlikely to exist. Anything expecting this path is doing it wrong.

**Comment by Mailaender** [comment]
What is the correct path?

**Comment by hfiguiere** [comment]
just let it be resolved by standard PATH, after you "enable", see https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/issues/36#issuecomment-1557684264
