### ISSUE TITLE
Add support for OpenJFX

### ISSUE THREAD

**Issue by x80486** [flathub/org.freedesktop.Sdk.Extension.openjdk11#4]
Instructions here: https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX/

There are some applications that require JavaFX – now OpenJFX.

Not sure if it's better to bundle it (as it was before) with the JDK itself, or having it as another extension – or something similar.

**Comment by mbooth101** [comment]
I've been thinking about this recently, and it could be simple to have openjfx built as a module as part of an application build.

Are you still interested in JavaFX?

**Comment by x80486** [comment]
I think it might be useful for someone else in the future, as of right now, including OpenFX is fairly simple. I was trying to use it for `Cryptomator`, but they are already bundling it.

I would wait for more audience since it's going to be another package/repo to maintain.

Thanks in any case :sunglasses:

**Comment by x80486** [comment]
Actually, I take that back...so if you have a change, include it also 🥳
