### ISSUE TITLE
Introduce patch to fix printing

### ISSUE THREAD

**Issue by guihkx** [flathub/org.freedesktop.Sdk.Extension.openjdk11#46]
**The problem:**

OpenJDK invokes `lp` / `lpr` (which are binaries part of CUPS) from a hard-coded path (`/usr/bin/lpr`), and as of now, those binaries are not present in the Freedesktop runtime, so any Java app that relies on printing functionality will fail.

Here are some upstream bug reports about it:

- https://bugs.openjdk.org/browse/JDK-4988591
- https://bugs.openjdk.org/browse/JDK-6520121
- https://bugs.openjdk.org/browse/JDK-8275923

There was even an attempt at fixing this problem in this pull request (but unfortunately it didn't go anywhere):

- https://github.com/openjdk/jdk/pull/6052

**A possible solution:**

I initially [reported](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1636) this to maintainers of the Freedesktop runtime, specifically asking them to include `lpr` with the runtime itself. I haven't got an answer yet.

So then I thought perhaps the path of least resistance would be including here a patch similar to the one from the OpenJDK pull request I just linked. I can send a pull request to include the patch here, but only if you guys think it's an acceptable solution.

---

I'm particularly interested in this patch because it would fix a problem with this proprietary, government-made app I'm the maintainer of:

- https://github.com/flathub/br.gov.fazenda.receita.irpf2023/issues/4

Thanks!

**Comment by Erick555** [comment]
This is fixed in freedesktop 23.08 runtime.
