### ISSUE TITLE
Should runtime be changed to 23.08?

### ISSUE THREAD

**Issue by faveoled** [flathub/org.freedesktop.Sdk.Extension.openjdk11#49]
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/blob/a6f5e77672c205702bf25e50c455171f6a7447ef/README.md?plain=1#L20C1-L20C31

**Comment by hfiguiere** [comment]
If you mean to update the README, just submit a pull request.

**Comment by guihkx** [comment]
>If you mean to update the README, just submit a pull request.

It's here: #50 

Please merge it (if you can).

**Comment by guihkx** [comment]
Done
