### ISSUE TITLE
Switching from openjdk10 to openjdk11 doesn't work on arch linux

### ISSUE THREAD

**Issue by deisi** [flathub/org.freedesktop.Sdk.Extension.openjdk11#8]
This is referring  to https://code.briarproject.org/nicoalt/briar-gtk/issues/1#login-pane

Both of us were trying to move a manifest file from openjdk10 to openjdk11 on arch linux. However we ran into trouble as flatpak-builder is telling us that openjdk11 extension is missing even tough it is installed. Up on building we get:

```
error: Requested extension org.freedesktop.Sdk.Extension.openjdk11 not installed
```
but at the same time:

```
$ flatpak list
Name                                Application ID                          Version    Branch Installation
....
OpenJDK 10 SDK extension            org.freedesktop.Sdk.Extension.openjdk10            1.6    system
OpenJDK 11 SDK extension            org.freedesktop.Sdk.Extension.openjdk11            18.08  system
```

any idea what is going on here?

CC: @altnico

**Comment by Erick555** [comment]
> org.gnome.Platform 3.28

3.28 version is outdated and unsupported. Moreover there is no openjdk11 compatible version with it. Please try org.gnome.Platform 3.32 instead.

**Comment by deisi** [comment]
Ah okay this solves the puzzle I think. Thx a lot.

Erick555 <notifications@github.com> schrieb am Do., 19. Sep. 2019, 17:03:
